config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  Blogo::Routes.mount_to(self, at: '/blog')
  resources :sections
  root to: 'sections#index'
  match 'contact' => 'sections#contact', :as => :contact, :via =>  :post
  devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :access, :rails_admin
    can :dashboard
    if user
      if user.role == "admin"
        can :manage, :all
      else
        can :manage, [Section]
      end
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base

	scope :main_address, -> { where(main_address: true).first }

	def address_with_coordinates
		Address.where(:lat.ne => [nil, "", " "], :lng.ne => [nil, "", " "]).last
	end
end

app/models/ally.rb
class Ally < ActiveRecord::Base
  mount_uploader :ally_logo, AllyLogoUploader
end

app/models/carrousel.rb
class Carrousel < ActiveRecord::Base
  mount_uploader :carrousel_image, CarrouselImageUploader
  enum text_alignment: [:arriba, :abajo]
  default_scope { order(:position => :asc) }
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  mount_uploader :client_logo, ClientLogoUploader
end

app/models/factory.rb
class Factory < ActiveRecord::Base
  mount_uploader :factory_image, FactoryImageUploader
  mount_uploader :factory_bg, FactoryBgUploader
  enum text_alignment: [:arriba, :abajo]
  default_scope { order(:position => :asc) }
end

app/models/header.rb
class Header < ActiveRecord::Base
  mount_uploader :bg_image, HeaderBgImageUploader
  mount_uploader :normal_image, HeaderNormalLogoImageUploader
  mount_uploader :thin_image, HeaderThinLogoImageUploader
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  mount_uploader :picture, PeoplePictureUploader
  default_scope { order(:position => :asc) }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/section.rb
class Section < ActiveRecord::Base
  enum section_type: [:carrusel, :fabricas, :aliados]

  mount_uploader :image, SectionImageUploader
  mount_uploader :bg_separator, BgSeparatorImageUploader
  
  before_save :set_formated_title, if: Proc.new { |section| section.title_changed? }

  default_scope { order(:position => :asc) }

  def set_formated_title
    self.formated_title = self.header_title.downcase.gsub(/[\d\W]/, "-")
  end
end

app/models/table_pay_link.rb
class TablePayLink < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify :before_add => :set_default_role
  enum role: [:user, :admin]
  # after_initialize :set_default_role, :if => :new_record?
  before_create :set_confirmation_token

  def set_default_role
    self.role ||= :user
  end

  def set_confirmation_token
    token = ([self.email] + SecureRandom.hex(6).chars).shuffle.join
    self.confirmation_token = token
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
    @header = Header.first
    @note = Note.first
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def contact
    if ContactMailer.contact_email(params).deliver_later
      render json: { success: true }, status: 200
    else
      render json: { success: false }, status: 404
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:title, :formated_title, :content)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	def static_map_for(size)
		lat = ENV['GENIE_LATITUDE']
		lng = ENV['GENIE_LONGITUDE']

	    params = {
	    	:center => [lat, lng].join(","),
	    	:zoom => 18,
	    	:size => size,
	    	:markers => [lat, lng].join(","),
	    	:sensor => true,
	    	:scale => 2
	    }

	    query_string =  params.map{|k,v| "#{k}=#{v}"}.join("&")
	    image_tag "http://maps.googleapis.com/maps/api/staticmap?#{query_string}", :alt => "Génie Consultoría SAS", :class => "genie-location"
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_allies.haml
%hr
%h1= section.allies_title
- Ally.all.each do |ally|
  .col-lg-2.each-ally
    .ally-picture
      = link_to ally.link, :target => "_blank" do
        = image_tag(ally.ally_logo)
    .ally-info.hide
      %p= ally.name

app/views/sections/_carrousel.haml
- slides = Carrousel.all
.container
  #myCarousel.col-lg-12.carousel.slide{"data-ride" => "carousel", :style => "background-color: #{section.background_color}"}
    / Indicators
    %ol.carousel-indicators
      - slides.count.times do |i|
        - li_klass = "#{i == 0 ? 'active' : nil}"
        %li{:class => li_klass, "data-slide-to" => i, "data-target" => "#myCarousel"}
    / Wrapper for slides
    .carousel-inner{:role => "listbox"}
      - slides.each do |slide|
        - item_klass = "#{slide.position == 1 ? 'active' : nil}"
        .item{:class => item_klass}
          = raw slide.carousel_content

app/views/sections/_clients.haml
%hr
%h1= section.clients_title
- Client.all.each do |client|
  .col-lg-1.each-client
    .client-picture
      = link_to client.link, :target => "_blank" do
        = image_tag(client.client_logo)
    .client-info.hide
      %p= client.name

app/views/sections/_contact_me.haml
/ %section#contact
/   .row
/     .col-lg-10.col-lg-offset-1
/       %form#contactForm{:name => "sentMessage", :novalidate => "", :data => {:url => contact_path}}
/         .row.control-group
/           .form-group.col-xs-12.floating-label-form-group.controls
/             %input#name.form-control{"data-validation-required-message" => t("contact.name_validation"), :placeholder => t("contact.name_placeholder"), :required => "", :type => "text"}/
/             %p.help-block.text-danger
/         .row.control-group
/           .form-group.col-xs-12.floating-label-form-group.controls
/             %input#email.form-control{"data-validation-required-message" => t("contact.email_validation"), :placeholder => t("contact.email_placeholder"), :required => "", :type => "email"}/
/             %p.help-block.text-danger
/         .row.control-group
/           .form-group.col-xs-12.floating-label-form-group.controls
/             %input#subject.form-control{"data-validation-required-message" => t("contact.subject_validation"), :placeholder => t("contact.subject_placeholder"), :required => "", :type => "text"}/
/             %p.help-block.text-danger
/         .row.control-group
/           .form-group.col-xs-12.floating-label-form-group.controls
/             %textarea#message.form-control{"data-validation-required-message" => t("contact.message_validation"), :placeholder => t("contact.message_placeholder"), :required => "", :rows => "1"}
/             %p.help-block.text-danger
/         #success
/         .row
/           .form-group.col-xs-12
/             %button.btn.btn-success.btn-lg{:type => "submit", :data => { :success => t("contact.success_message"), :error => t("contact.error_message") }}= t("contact.submit")

- bg_color = @note.present? ? @note.bg_color : "#ffffa5"
- text_color = @note.present? ? @note.text_color : "#000000"

.quote-container
  /%i.pin
  %blockquote.note{:style => "background-color: #{bg_color}"}

    %form#contactForm{:name => "sentMessage", :novalidate => "", :data => {:url => contact_path}}

      %input#name.form-control{"data-validation-required-message" => t("contact.name_validation"), :placeholder => t("contact.name_placeholder"), :required => "", :type => "text", :style => "color: #{text_color}"}
      %p.help-block.text-danger

      %input#email.form-control{"data-validation-required-message" => t("contact.email_validation"), :placeholder => t("contact.email_placeholder"), :required => "", :type => "email", :style => "color: #{text_color}"}
      %p.help-block.text-danger

      %input#subject.form-control{"data-validation-required-message" => t("contact.subject_validation"), :placeholder => t("contact.subject_placeholder"), :required => "", :type => "text", :style => "color: #{text_color}"}
      %p.help-block.text-danger

      %textarea#message.form-control{"data-validation-required-message" => t("contact.message_validation"), :placeholder => t("contact.message_placeholder"), :required => "", :rows => "1", :style => "color: #{text_color}"}
      %p.help-block.text-danger

      #success
      
      %button.btn.btn-success.btn-lg{:type => "submit", :data => { :success => t("contact.success_message"), :error => t("contact.error_message") }}= t("contact.submit")

app/views/sections/_factories.haml
- Factory.all.each do |factory|
  .col-lg-3.each-factory
    %h3.name= factory.name
    .factory{:style => "background-color: #{factory.bg_color}"}
      = image_tag(factory.factory_image)
    .factory-hover.hide{:style => "background-image: url(#{factory.factory_image.url})"}
      .text
        %h3= factory.title
        %p= raw factory.description

app/views/sections/_form.html.haml
= form_for @section do |f|
  - if @section.errors.any?
    #error_explanation
      %h2= "#{pluralize(@section.errors.count, "error")} prohibited this section from being saved:"
      %ul
        - @section.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :formated_title
    = f.text_field :formated_title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/sections/_location.haml
- main_address = Address.where(:main_address => true).last
- lat = main_address.present? ? main_address.lat : "5.0468017"
- lng = main_address.present? ? main_address.lng : "-75.4827315"

:javascript

  function initMap() {
    var myLatLng = {lat: #{lat}, lng: #{lng}};

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: myLatLng
    });

    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      title: 'Génie'
    });
  }

%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyDIdyiobaMh2FTUdbLurIYN8XiK_2kAT1E&callback=initMap"}

%footer.text-center#contact
  .footer-above
    .container
      .section-blank
      .row
        .col-lg-12
          .col-lg-7.hidden-xs
            #map{:style => "width:600px; height:300px; border:0;"}
            / %iframe{:allowfullscreen => "", :frameborder => "0", :height => "306", :src => "https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d387.08444246173525!2d-75.48270416499281!3d5.046664712813898!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses-419!2sco!4v1455940578542", :style => "border:0", :width => "600"}
          .col-lg-5
            = render :partial => "sections/contact_me"

        .col-lg-12.extra-info
          .footer-col.col-md-3
            %h3 Dirección
            - Address.all.each do |address|
              %p= address.address_line_1
              %p= address.address_line_2
              %p= address.city
              %br
          .footer-col.col-md-3
            %h3 Redes Sociales
            %ul.list-inline
              %li
                %a.btn-social.btn-outline{:href => "http://www.facebook.com/Genieconsultoria", :target => "_blank"}
                  %span.icon-facebook
              %li
                %a.btn-social.btn-outline{:href => "http://www.twitter.com/genieconsultor", :target => "_blank"}
                  %span.icon-twitter
          .footer-col.col-md-3
            %h3 Contacto
            %p= Address.main_address.try(:contact_email) || "genie@genieconsultoria.com"
            %br
            - Address.all.each do |address|
              %p= address.phone
              %p= address.mobile
              %br
          .footer-col.col-md-3.links
            %h3 Enlaces
            - Link.all.each do |link|
              %a.col-lg-12{:href => link.link, :target => "_blank"}
                %span= link.name

  .footer-below
    .container
      .row
        .col-lg-12
          © 2014 Génie Consultoría SAS. Manizales - Caldas - Colombia

app/views/sections/_people.haml
%h1= section.genies_title
- Person.all.each do |person|
  .col-lg-4.each-person
    .person-effects
      .person-picture
        = image_tag(person.picture)
      .person-info
        %p.rol= person.rol
        %p= person.passion
    - if person.linkedin_url.present?
      %a.person-name{:href => person.linkedin_url}
        = person.name
        %span.icon-linkedin
    - else
      %p.person-name= person.name

app/views/sections/_top.haml
%body#page-top.index
  %nav.navbar.navbar-default.navbar-fixed-top{:style => "background-color: #{@header.bg_color}; background-image: url(#{@header.bg_image.url})"}
    .container
      .navbar-header.page-scroll.col-lg-4
        %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        / %a.navbar-brand{:href => "#page-top"} génie
        %a.navbar-brand{:href => "#page-top"}
          = image_tag(@header.normal_image, :class => "img-responsive genie-logo")
          = image_tag(@header.thin_image, :class => "img-responsive genie-slogan hide")

      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li.hidden
            %a{:href => "#page-top", :style => "{color: #{@header.link_color}} :hover {color: #{@header.link_hover_color}}; text-align: center; padding-top: 10px;"}
          - @sections.each do |section|
            - if section.header_title.present?
              %li.page-scroll{:style => "width: #{@header.links_width}; border-left: 1px #{@header.border_color} solid; height: 40px; margin-top: 10px;"}
                %a{:href => "##{section.formated_title}", :style => "{color: #{@header.link_color}} :hover {color: #{@header.link_hover_color}}; text-align: center; padding-top: 10px;"}= section.header_title
          %li.page-scroll{:style => "width: #{@header.links_width}; border-left: 1px #{@header.border_color} solid; height: 40px; margin-top: 10px;"}
            %a{:href => "#contact", :style => "color: {#{@header.link_color}} :hover {color: #{@header.link_hover_color}}; text-align: center; padding-top: 10px;"}= t("contact.title")
          %li.page-scroll.hidden-md{:style => "width: #{@header.links_width}; border-left: 1px #{@header.border_color} solid; border-right: 1px #{@header.border_color} solid; height: 40px; margin-top: 10px;"}
            %a{:href => "https://genieconsultoriablog.wordpress.com/", :style => "{color: #{@header.link_color}} :hover {color: #{@header.link_hover_color}}; text-align: center; padding-top: 10px;", :target => "_blank"} Blog
          %li.page-scroll.hidden-lg.hidden-md{:style => "width: #{@header.links_width}; border-left: 1px #{@header.border_color} solid; border-right: 1px #{@header.border_color} solid; height: 40px; margin-top: 10px;"}
            %a{:href => "https://www.zonapagos.com/t_genie/pagos.asp", :style => "{color: #{@header.link_color}} :hover {color: #{@header.link_hover_color}}; text-align: center; padding-top: 10px;", :target => "_blank"} 
              Pagos
            

app/views/sections/edit.html.haml
%h1 Editing section

= render 'form'

= link_to 'Show', @section
\|
= link_to 'Back', sections_path

app/views/sections/index.html.haml
= render :partial => "sections/top"

- @sections.each do |section|
  - bg_color = section.background_color.present? ? "background-color:#{section.background_color}" : ""
  - title_color = section.title_color.present? ? "color:#{section.title_color}" : ""
  - text_color = section.text_color.present? ? "color:#{section.text_color}" : ""

  - if section.color_separator.present?
    .separator{:style => "background-color:#{section.color_separator}"}
  - elsif section.bg_separator.present?
    .separator{:style => "background-image:#{section.bg_separator}"}


  - if section.section_blank.present?
    - klass = "section-blank"
  - else
    - klass = "half-blank-section"

  - if section.section_type == "carrusel"
    %section.carousel-container{:id => "#{section.formated_title}", :style => "#{bg_color}"}
      %div{:class => klass}
      .col-lg-12
        = render :partial => "sections/carrousel", :locals => {:section => section}
  - elsif section.section_type == "fabricas"
    %section.modales-container{:id => "#{section.formated_title}", :style => "#{bg_color}"}
      %div{:class => klass}
      .col-lg-12
        = render :partial => "sections/factories", :locals => {:section => section}
  - elsif section.section_type == "aliados"
    %section.clients-container{:id => "#{section.formated_title}", :style => "#{bg_color}"}
      %div{:class => klass}
      .col-lg-12
        = render :partial => "sections/people", :locals => {:section => section}
      .col-lg-12
        = render :partial => "sections/allies", :locals => {:section => section}
      .col-lg-12
        = render :partial => "sections/clients", :locals => {:section => section}
  - else
    %section{:id => "#{section.formated_title}", :style => "#{bg_color}"}
      .container
        %div{:class => klass}
        .text-center{:style => "#{title_color}"}
          %h2= section.title
        .row{:style => "#{text_color}"}
          = raw section.content

= render :partial => "sections/location"

app/views/sections/new.html.haml
%h1 New section

= render 'form'

= link_to 'Back', sections_path

app/views/sections/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @section.title
%p
  %b Formated title:
  = @section.formated_title
%p
  %b Content:
  = @section.content

= link_to 'Edit', edit_section_path(@section)
\|
= link_to 'Back', sections_path